use_frameworks!

target 'Networking_Example' do
  pod 'Networking', :path => '../'
  pod 'NetworkingRXSwift', :path => '../'

  target 'Networking_Tests' do
    inherit! :search_paths

    
  end
end
